paths:
  model_dir : working_dir/model_new/InceptionResnetV2_2017_test
  inference_dir : working_dir/model_new/infer_dir
  eval_dir : working_dir/model_new/eval_dir
  cache_dir : working_dir/examples/CMMD_cache_dir
  data_misc_dir : working_dir/data_misc
  data_split_filename:  cmmd_split.pkl
  data_dir : ${oc.env:CMMD_DATA_PATH}
run:
  running_modes : ['train', 'infer', 'eval']
train:
  target : classification
  reset_cache: False
  num_workers : 10
  num_folds : 5
  train_folds : [0,1,2]
  validation_folds : [3]
  batch_size: 2
  learning_rate : 1e-4
  weight_decay :  0
  resume_checkpoint_filename :
  trainer:
    accelerator : gpu
    devices : 1
    num_epochs : 100
    ckpt_path :
infer:
  infer_filename : validation_set_infer.gz
  checkpoint : best_epoch.ckpt
  infer_folds : [4]
  target : classification
  num_workers : 12
