defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

task : classification
cls_targets : [V00COHORT,gender]
train_folds : [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
val_folds : [16,17,18,19]
test_folds : []
cuda_devices : [0]
batch_size : 8
backbone : unet3d
precision : 32
resize_to : [40,224,224]
csv_path : data/relevant_dicoms.csv #fill
results_dir : results #fill

n_workers : 24

clearml : False
clearml_project_name : OAI/downstream

experiment : oai_classification

grad_clip : 0
learning_rate : 0.001
n_epochs : 400
weight_decay : 0.001
reset_cache : False
debug : False
suprem_weights : null # if pretrained=True a path need to be filled. can download from https://github.com/MrGiovanni/SuPreM
dino_weights : null
mae_weights : null
resume_training_from : null #resume training from checkpoint
test_ckpt : null # if not null - an evaluation on the test set will be performed using the test_ckpt
