defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

task : segmentation
batch_size : 2
accumulate_grad_batches : 1
precision : 32
backbone : unet3d
num_classes : 7 # including background
resize_to : [40, 224,224]
csv_path : data/seg_oai.csv #fill
results_dir : results #fill
train_folds : [train]
val_folds : [val]
test_folds : [test]
cuda_devices : [0]
split_pth : null #fill

n_workers : 24
clearml : False
clearml_project_name : OAI/downstream
experiment : oai_segmentation

include_background : false
sigmoid : True
softmax : False

aug : True
grad_clip : 0
learning_rate : 0.0005
n_epochs : 3000
weight_decay : 0.001
reset_cache : False
debug : False
tags : [segmentation]
suprem_weights : weights/supervised_suprem_unet_2100.pth # if pretrained=True a path need to be filled. can download from https://github.com/MrGiovanni/SuPreM
dino_weights : null
resume_training_from : null #resume training from checkpoint
test_ckpt : null # if not null - an evaluation on the test set will be performed using the test_ckpt
save_test_results : true
