defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

task : mae
batch_size : 32
backbone : efficientnet-b3 # unet3d for 3d mae

resize_to : null #[40, 224,224]
csv_path : /dccstor/mm_hcls2/oai/code/data/relevant_dicoms.csv

mae_cfg :
  mask_percentage : 0.4
  cuboid_size : [2,2] # should have 2/3 dims depending on mae2d/mae3d
results_dir : /dccstor/mm_hcls2/oai/results
n_workers : 24
clearml : True
clearml_project_name : OAI/Dino

train_folds : [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
val_folds : [19]
cuda_devices : [0]

experiment : debug_mae2d

grad_clip : 0
learning_rate : 0.000005
n_epochs : 1000
weight_decay : 0.001
reset_cache : False
debug : False
ckpt_path : no_path
pretrained : True
pretrained_path : null # fill suprem weights path in the mae3d
log_grad_norm : False
tags : [mae]
