exp_name : "delete"
experiment_num : 2
task_num : task_1 # task_1 or task_2 
num_gpus : 1
use_data : {"imaging": True, "clinical": True} 
batch_size : 2
resize_to : [70, 256, 256]
num_epochs : 70
learning_rate : 0.00005
imaging_dropout : 0.5
fused_dropout : 0.5
pretrained : False
regression_head : True
two_dim : False
testing : False # for testing\continous integration

task_1:
  num_classes : 2
  target_name : "data.gt.gt_global.task_1_label"
  target_metric : "validation.metrics.auc"

task_2:
  num_classes : 5
  target_name : "data.gt.gt_global.task_2_label"
  target_metric : "validation.metrics.auc" #.macro_avg"
