exp_name : "testing-pretrained-med3d"
experiment_num : 0 # 0 - self-norm | 2 - regular
task_num : task_1 # task_1 or task_2 
num_gpus : 1
use_data : {"imaging": True, "clinical": True} 
batch_size : 3
resize_to : [70, 256, 256]
num_epochs : 120
learning_rate : 0.00005
imaging_dropout : 0.5
fused_dropout : 0.5
pretrained : True
regression_head : False
two_dim : False
reset_cache : True
gpus : [3]
testing : False # for testing\continous integration

task_1:
  num_classes : 2
  target_name : "data.gt.gt_global.task_1_label"
  target_metric : "validation.metrics.auc"

task_2:
  num_classes : 5
  target_name : "data.gt.gt_global.task_2_label"
  target_metric : "validation.metrics.auc" #.macro_avg"
