from collections import OrderedDict
import pathlib
import os
import yaml
import argparse
from typing import Dict

import pandas as pd
from fuse.dl.models import ModelMultiHead
from fuse.dl.models.backbones.backbone_resnet_3d import BackboneResnet3D
from fuse.dl.models.heads.heads_3D import Head3D
from fuseimg.datasets.knight import KNIGHTDataModule
import torch.nn.functional as F
import torch.nn as nn

from fuse.eval.metrics.classification.metrics_classification_common import MetricAUCROC, MetricAccuracy, MetricConfusion
from fuse.eval.metrics.classification.metrics_thresholding_common import MetricApplyThresholds
import torch.optim as optim
import copy
from fuse.dl.losses.loss_default import LossDefault
from fuse.dl.lightning.pl_module import LightningModuleDefault
import pytorch_lightning as pl

## Parameters:
##############################################################################
# Data sources to use in model. Set {'imaging': True, 'clinical': False} for imaging only setting,
# and vice versa, or set both to True to use both.
# allocate gpus
# uncomment if you want to use specific gpus instead of automatically looking for free ones


def make_model(
    use_data: dict, num_classes: int, imaging_dropout: float, fused_dropout: float
) -> LightningModuleDefault:
    if use_data["imaging"]:
        backbone = BackboneResnet3D(in_channels=1, pretrained=False)
        conv_inputs = [("model.backbone_features", 512)]
    else:
        backbone = nn.Identity()
        conv_inputs = None
    if use_data["clinical"]:
        append_features = [("data.input.clinical.all", 11)]
    else:
        append_features = None

    model = ModelMultiHead(
        conv_inputs=(("data.input.img", 1),),
        backbone=backbone,
        heads=[
            Head3D(
                head_name="head_0",
                mode="classification",
                conv_inputs=conv_inputs,
                dropout_rate=imaging_dropout,
                num_outputs=num_classes,
                append_features=append_features,
                append_layers_description=(256, 128),
                fused_dropout_rate=fused_dropout,
            ),
        ],
    )
    return model


def main(cfg: Dict) -> None:
    # set constant seed for reproducibility.
    pl.seed_everything(1234)

    task_num = cfg["task_num"]
    num_classes = cfg[task_num]["num_classes"]
    target_name = cfg[task_num]["target_name"]
    class_names = None if not cfg[task_num]["class_names"] else cfg[task_num]["class_names"]

    # read train/val splits file. for convenience, we use the one
    # auto-generated by the nnU-Net framework for the KiTS21 data
    dir_path = pathlib.Path(__file__).parent.resolve()
    splits = pd.read_pickle(os.path.join(dir_path, "splits_final.pkl"))
    # For this example, we use split 0 out of the 5 available cross validation splits
    split = splits[0]
    if cfg["testing"]:
        split["train"] = split["train"][:10]
        split["val"] = split["val"][:10]
    # read environment variables for data, cache and results locations
    data_path = os.environ["KNIGHT_DATA"]
    cache_path = "/dccstor/mm_hcls/shatz/knight/cache/"
    # cache_path = os.path.join(os.environ["KNIGHT_CACHE"], str(cfg["experiment_num"]))
    results_path = "/dccstor/mm_hcls/shatz/knight/results/"
    # results_path = os.environ["KNIGHT_RESULTS"]

    ## Basic settings:
    ##############################################################################
    # create model results dir:
    # we use a time stamp in model directory name, to prevent re-writing
    model_dir = results_path
    # timestr = time.strftime("%Y%m%d-%H%M%S")
    # model_dir = os.path.join(results_path, timestr)
    # if not os.path.isdir(model_dir):
    #     os.makedirs(model_dir)
    # shutil.copy(cfg_path, model_dir)
    # start logger
    # fuse_logger_start(output_path=model_dir, console_verbose_level=logging.INFO)

    ## Model definition
    ##############################################################################
    model = make_model(cfg["use_data"], num_classes, cfg["imaging_dropout"], cfg["fused_dropout"])

    ## FuseMedML dataset preparation
    ##############################################################################
    knight_dm = KNIGHTDataModule(
        num_workers=cfg["num_workers"],
        batch_size=cfg["batch_size"],
        data_path=data_path,
        cache_dir=cache_path,
        split=split,
        reset_cache=cfg["reset_cache"],
        resize_to=cfg["resize_to"],
        shuffle=False,
        drop_last=False,
        use_batch_sampler=True,
        target_name=target_name,
        num_classes=num_classes,
        task_num=task_num,
    )

    # Loss definition:
    ##############################################################################
    losses = {
        "cls_loss": LossDefault(pred="model.logits.head_0", target=target_name, callable=F.cross_entropy, weight=1.0),
    }

    # Metrics definition:
    ##############################################################################
    train_metrics = OrderedDict(
        [
            ("op", MetricApplyThresholds(pred="model.output.head_0")),  # will apply argmax
            ("auc", MetricAUCROC(pred="model.output.head_0", target=target_name, class_names=class_names)),
            ("accuracy", MetricAccuracy(pred="results:metrics.op.cls_pred", target=target_name)),
            (
                "sensitivity",
                MetricConfusion(pred="results:metrics.op.cls_pred", target=target_name, metrics=("sensitivity",)),
            ),
        ]
    )
    val_metrics = copy.deepcopy(train_metrics)  # use the same metrics in validation as well

    best_epoch_source = dict(
        monitor=cfg[task_num]["target_metric"],  # can be any key from losses or metrics dictionaries
        mode="max",  # can be either min/max
    )

    # Optimizer definition:
    ##############################################################################
    optimizer = optim.Adam(model.parameters(), lr=cfg["learning_rate"], weight_decay=0.001)

    # Scheduler definition:
    ##############################################################################
    lr_scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer)
    lr_sch_config = dict(scheduler=lr_scheduler, monitor="validation.losses.total_loss")
    optimizers_and_lr_schs = dict(optimizer=optimizer, lr_scheduler=lr_sch_config)

    ## Training
    ##############################################################################

    # create instance of PL module - FuseMedML generic version
    pl_module = LightningModuleDefault(
        model_dir=model_dir,
        model=model,
        losses=losses,
        train_metrics=train_metrics,
        validation_metrics=val_metrics,
        best_epoch_source=best_epoch_source,
        optimizers_and_lr_schs=optimizers_and_lr_schs,
    )
    # create lightining trainer.
    pl_trainer = pl.Trainer(
        default_root_dir=model_dir,
        max_epochs=cfg["num_epochs"],
        accelerator=cfg["accelerator"],
        devices=cfg["num_devices"],
        num_nodes=cfg["num_nodes"],
        strategy="ddp" if (cfg["num_devices"] > 1) or (cfg["num_nodes"] > 1) else None,
        num_sanity_val_steps=-1,
    )

    # train
    pl_trainer.fit(pl_module, knight_dm, ckpt_path=None)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--num_nodes", type=int, default=None)
    parser.add_argument("--num_devices", type=int, default=None)
    args = parser.parse_args()

    # read config
    config_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "config.yaml")
    cfg = yaml.safe_load(open(config_path))

    # override num_nodes and num_devices if passed as an arg
    if args.num_nodes:
        cfg["num_nodes"] = args.num_nodes
    if args.num_devices:
        cfg["num_devices"] = args.num_devices

    main(cfg)
